version: '3'

tasks:
  install:
    desc: Install dependencies.
    cmds:
      - poetry install --no-root

  fmt:
    desc: Run linting and fix issues.
    cmds:
      - poetry run black .
      - poetry run ruff check turtle_api tests --fix

  lint:
    desc: Run linting tasks.
    cmds:
      - poetry run black .
      - poetry run ruff check turtle_api tests
      - poetry run mypy turtle_api

  test:
    desc: Run unit and integration tests
    cmds:
      - poetry run pytest tests/unit tests/integration

  test-cov:
    desc: Run unit and integration tests with coverage
    cmds:
      - poetry run pytest --cov turtle_api --cov-report term --cov-report html:test_results/cov_html --cov-report xml:test_results/cov.xml tests/unit tests/integration
